# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4c7ca667b2b03648f30a6c4ccfacf21f776f586d492af51b9deb148a8c0c21301bea60bb175343fb064599adfa2d851e547499c9be0efc10195c201abb7254

test:
  secret_key_base: 73daad90c752ff93bed17e64a6ee579c0ddd378875d7477535dbecd934b385de2a36009eccc13506b2e8640542fac237d6aca62dc680ab88afa52dbc722528d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
